### ISSUE TITLE
FileNotFoundError: No file './images/not_find_virus.png' found in working directory 'C:\Users\~~\Downloads\Compressed\PythonOS-main_2\PythonOS-main'.

### ISSUE THREAD

**Issue by happyleibniz** [Github-Huangshaoqi/PythonOS#1]
Traceback (most recent call last):
  File "C:\Users\leibniz\Downloads\Compressed\PythonOS-main_2\PythonOS-main\shell_startup copy.py", line 571, in <module>
    start_computer()
  File "C:\Users\leibniz\Downloads\Compressed\PythonOS-main_2\PythonOS-main\shell_startup copy.py", line 422, in start_computer
    start()
  File "C:\Users\leibniz\Downloads\Compressed\PythonOS-main_2\PythonOS-main\shell_startup copy.py", line 373, in start
    user_defalt()
  File "C:\Users\leibniz\Downloads\Compressed\PythonOS-main_2\PythonOS-main\shell_startup copy.py", line 251, in user_defalt
    not_found_virus=pygame.image.load("./images/not_find_virus.png")
FileNotFoundError: No file './images/not_find_virus.png' found in working directory 'C:\Users\leibniz\Downloads\Compressed\PythonOS-main_2\PythonOS-main'.

**Comment by happyleibniz** [comment]
建议把not_find_virus.png，beat_microsoft_to_death.png，win_script.png，mswinerr.png移回来

**Comment by Github-Huangshaoqi** [comment]
eee,好吧
